# Generated by Django 4.2 on 2023-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_post_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='addressee',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('Танк', 'Танк'), ('Хил', 'Хил'), ('ДД', 'ДД'), ('Гилдмастер', 'Гилдмастер'), ('Квестгивер', 'Квестгивер'), ('Кузнец', 'Кузнец'), ('Кожевник', 'Кожевник'), ('Зельевар', 'Зельевар'), ('Мастер заклинаний', 'Мастер заклинаний')], default='Танк', max_length=17),
        ),
    ]
